package com.ibm.gtmpa.domain.enumeration;

public enum MilestoneTypeEnum {
	agreedGTMMilestone,proposalMilestone,initialDiscussionMilestone,salesCompetencyMilestone,preSalesCompetencyMilestone,
technicalCompetencyMilestone,solutionArchitectedMilestone,solutionCostedMilestone,
solutionCollateralMilestone,marketingCollateralMilestone,marketingPlanMilestone,campaignPlanMilestone

}